### ISSUE TITLE
Many warnings without elf

### ISSUE THREAD

**Issue by mrx23dot** [govind-mukundan/MapViewer#16]
I would expect max one pop up but getting:

![2023-10-16_210835_VU](https://github.com/govind-mukundan/MapViewer/assets/4163396/6f8c5906-7204-4d0e-a6e5-659e778a17b1)

**Comment by govind-mukundan** [comment]
thanks, have fixed that. Looks like at some point I forgot about the case where we don't have the NM/ELF
