### ISSUE TITLE
Error Analyzing Map File 

### ISSUE THREAD

**Issue by yabskbd** [govind-mukundan/MapViewer#17]
Getting the below error. Made sure there is no space or special character in the path file and gave full path to map file, elf file and NM/ELF reader paths. Also tried running as administrator. Can you point me to the issue? 

Thank You in advance  

![image](https://github.com/govind-mukundan/MapViewer/assets/11657199/a69b10e0-6705-410f-822c-786264e7819e)
![image](https://github.com/govind-mukundan/MapViewer/assets/11657199/11b4797c-a8a1-407d-a8f9-bee44146d8be)

**Comment by govind-mukundan** [comment]
The problem is not with the path for the tools, it's the path of one of more or the files in your project. You could run it in debug mode to see which file path is causing the problem.

**Comment by yabskbd** [comment]
How do you run in debug mode?

**Comment by govind-mukundan** [comment]
> How do you run in debug mode?
> 
> 

Download visual studio community edition and open the .sln file in the project
