### ISSUE TITLE
mapviewer lags when using module filters

### ISSUE THREAD

**Issue by teckcodsup** [govind-mukundan/MapViewer#6]
when using module filter mapviewer lags and it starts to have high cpu usage
note i use mapviewer with gnu arm toolchain (gcc-arm-none-eabi) which has NM and READELF

**Comment by govind-mukundan** [comment]
Could you attach the map and elf files along with the tools, would make it easy for me to debug

**Comment by teckcodsup** [comment]
the code belongs to the company but  this a hello world example generated by the same tools and it presents the same issue but not as fast as for the other code ( due to size maybe )
[files.zip](https://github.com/govind-mukundan/MapViewer/files/3686143/files.zip)

**Comment by teckcodsup** [comment]
sorry there is another tool rather than arm-none-eabi-gcc-nm it is called arm-none-eabi-nm i changed it but the problem remains
[tool.zip](https://github.com/govind-mukundan/MapViewer/files/3686624/tool.zip)

**Comment by govind-mukundan** [comment]
thanks, I will have a look at it tomorrow

**Comment by govind-mukundan** [comment]
Could you try with this version of the exe?
[Debug.zip](https://github.com/govind-mukundan/MapViewer/files/3688941/Debug.zip)

**Comment by teckcodsup** [comment]
thank you very much, i dont have the problem anymore ( at least during the 1h since i downloaded the zip file) one more question did you use arm-none-eabi-gcc-nm or arm-none-eabi-nm or is it the same ???
a final request could you upload the visual studio solution version so maybe in future i can add some features 
again thank you very much your application is very beneficial

**Comment by govind-mukundan** [comment]
I used `arm-none-eabi-nm`, the gcc one was throwing some missing DLL error. They are probably the same in terms of functionality.

Yes I will update the project soon once consolidate the changes and let you know. Thanks!

**Comment by teckcodsup** [comment]
i have a question is the classification to bss,text,data in the symbol side independent from my own settings ( is only dependant on the tools )
thank you

**Comment by govind-mukundan** [comment]
Do you mean the calculations shown above the "Symbols" tab? These are dependent on the output of NM, not on your settings. NM has some ["standard" ways of reporting the symbols](https://linux.die.net/man/1/nm) - for example `d`, `g` are in the Data section etc I have just classified them based on that. 

The user configured settings are relevant for the information in the "Modules" tab on the left and depend on your linker script.

**Comment by teckcodsup** [comment]
thank you very much

**Comment by govind-mukundan** [comment]
I've pushed the changes into the [ui-fixes](https://github.com/govind-mukundan/MapViewer/commits/ui-fixes) branch. Will merge them on to master next week.

**Comment by govind-mukundan** [comment]
Fixed in [v0.3](https://github.com/govind-mukundan/MapViewer/releases/tag/v0.3)
