### ISSUE TITLE
Fails to populate olv_SymbolView 

### ISSUE THREAD

**Issue by deyspandan** [govind-mukundan/MapViewer#7]
Sorry I am a noob programmer (specially C#)

When I click on a file on the left it does not populate the list on the right
![image](https://user-images.githubusercontent.com/10828292/70539127-87aa0400-1b63-11ea-8a04-3c5736a1f4ad.png)

the problem seems to arise because
- s.ModuleName is empty
- hence m1 is empty (in l.660)
- and assertion on l.662 fails
![image](https://user-images.githubusercontent.com/10828292/70539627-40704300-1b64-11ea-939b-bc505f619d3b.png)

any idea why this is happening?

**Comment by govind-mukundan** [comment]
For some reason the program couldn't parse the module name of the symbol `acknowledge`. You could add a simple empty string check to make the exception go away, for example:

```
            List<Symbol> syms = mods.SelectMany(m => _syms.Symbols.Where(s =>
            {
                if (m.ModuleName == "") return false;  // NEW
```
But as to why it couldn't find the module name - we have to look into the input files, most likely the regular expression for parsing the module name requires some update or the name is not available in the files. If you attach the files (and exe's if you are using NM/ReadELF) I can take a look.

**Comment by deyspandan** [comment]
Tried adding this line, but it is not helping

> if (m.ModuleName == "") return false;  // NEW



My platform is Windows 10 v1903
I am working on a PIC32MX5XX/6XX/7XX MCU with compiler XC32 v1.40

I have added all the files in the zip -> [MapAnalysis.zip](https://github.com/govind-mukundan/MapViewer/files/3950437/MapAnalysis.zip)

- ReadElf -> xc32-elfedit.exe
- NM -> xc32-nm.exe
- AN1388 Source Code 2014_02_14.zip -> all the source files
    - Unzip this here "C:\microchip\"
    - check myApplication.config to get the paths
- myApplication.config -> which i modified to suit PIC32
- map file -> .map
- elf file -> ETH_Btl_ETH_StarterKit.X.production.elf
- hex file -> ETH_Btl_ETH_StarterKit.X.production.hex

**Comment by govind-mukundan** [comment]
Thanks for the files, I'm not able to run the `*.exe`, I think I might need some accompanying DLLs or so. Could you zip the entire folder where the ,exe's are stored? Or send me a link to the version of the PIC32 compiler you are using, I can install it locally and check.

**Comment by deyspandan** [comment]
Here you go in case you need the installer

https://we.tl/t-bwfKHqhrln

**Comment by govind-mukundan** [comment]
I'm not able to reproduce the exception. I can see the files as expected. But I notice that there is a difference between the sizes shown in your screenshot with what I have. Did you send me the wrong .elf file/project?

![image](https://user-images.githubusercontent.com/2495855/70843904-75d2a480-1e74-11ea-9a88-bc368a383fe3.png)

- Also you should use the program `xc32-readelf.exe` instead of `xc32-elfedit.exe`

**Comment by deyspandan** [comment]
> Also you should use the program xc32-readelf.exe instead of xc32-elfedit.exe

This was the issue (facepalm)

Thanks for pointing out you owe some beer, let me how to send you one!

**Comment by govind-mukundan** [comment]
Well you could use [PayPal](https://www.paypal.me/govindmukundan)
